CONTAINER Ocontainer
{
  NAME Ocontainer;
  INCLUDE Obase;
  GROUP ID_OBJECTPROPERTIES
  {
    GROUP {
      LAYOUTGROUP;
      COLUMNS 3;
      GROUP
      {
        BUTTON NRCONTAINER_CHILDREN_HIDE { SCALE_H; }
        BUTTON NRCONTAINER_TAGS_HIDE { SCALE_H; }
        BUTTON NRCONTAINER_ICON_LOAD { SCALE_H; }
        BUTTON NRCONTAINER_PROTECT { SCALE_H; }
      }
      GROUP
      {
        BUTTON NRCONTAINER_CHILDREN_SHOW { SCALE_H; }
        BUTTON NRCONTAINER_TAGS_SHOW { SCALE_H; }
        BUTTON NRCONTAINER_ICON_CLEAR { SCALE_H; }
      }
    }
    SEPARATOR { LINE; }
    STATICTEXT NRCONTAINER_DEVINFO { }
    BUTTON NRCONTAINER_VISITDEV { }
  }
  GROUP NRCONTAINER_INFO {
    STRING NRCONTAINER_INFO_NAME { }
    STRING NRCONTAINER_INFO_VERSION { }
    STRING NRCONTAINER_INFO_URL { }
    STRING NRCONTAINER_INFO_AUTHOR { }
    STRING NRCONTAINER_INFO_AUTHOR_EMAIL { }
    STRING NRCONTAINER_INFO_DESCRIPTION { CUSTOMGUI MULTISTRING; }
  }
}
