CONTAINER Ocontainer
{
  NAME Ocontainer;
  INCLUDE Obase;
  GROUP ID_OBJECTPROPERTIES
  {
    LAYOUTGROUP;
    COLUMNS 3;
    GROUP
    {
      BUTTON NRCONTAINER_CHILDREN_HIDE { SCALE_H; }
      BUTTON NRCONTAINER_TAGS_HIDE { SCALE_H; }
    }
    GROUP
    {
      BUTTON NRCONTAINER_CHILDREN_SHOW { SCALE_H; }
      BUTTON NRCONTAINER_TAGS_SHOW { SCALE_H; }
    }
    GROUP
    {
      STATICTEXT NRCONTAINER_CHILDREN_INFO {}
      STATICTEXT NRCONTAINER_TAGS_INFO {}
    }
    GROUP
    {
      BUTTON NRCONTAINER_ICON_LOAD { SCALE_H; }
    }
    GROUP
    {
      BUTTON NRCONTAINER_ICON_CLEAR { SCALE_H; }
    }
  }
}
