
#ifndef Ocontainer_H
#define Ocontainer_H

enum
{
  Ocontainer = 1029700,

  NRCONTAINER_DEV_INFO = 2011,            // STATICTEXT

  NRCONTAINER_HIDE_TAGS = 2001,           // BOOL
  NRCONTAINER_HIDE_MATERIALS = 2002,      // BOOL
  NRCONTAINER_GENERATOR_CHECKMARK = 2006, // BOOL
  NRCONTAINER_ICON_LOAD = 2003,           // BUTTON
  NRCONTAINER_ICON_CLEAR = 2004,          // BUTTON
  NRCONTAINER_PACKUP = 2005,              // BUTTON

  NRCONTAINER_INFO = 2020,                // GROUP
  NRCONTAINER_INFO_NAME = 2021,           // STRING
  NRCONTAINER_INFO_VERSION = 2022,        // STRING
  NRCONTAINER_INFO_URL = 2023,            // STRING
  NRCONTAINER_INFO_AUTHOR = 2024,         // STRING
  NRCONTAINER_INFO_AUTHOR_EMAIL = 2025,   // STRING
  NRCONTAINER_INFO_DESCRIPTION = 2026,    // STRING

  // Next ID: 2027
};

#endif // Ocontainer_H

