
#ifndef c4d_symbols_H
#define c4d_symbols_H

enum {
  IDC_OCONTAINER,
  IDC_LOADCUSTOMICONDIALOG,
  IDC_OUTOFMEMORY,
  IDC_INVALIDIMAGE,
  IDC_LOADCONTAINER_LOADTITLE,
  IDC_LOADCONTAINER_INVALIDFILE,
  IDC_PASSWORDSDONTMATCH,
  IDC_COMMAND_LOADCONTAINER_TITLE,
  IDC_COMMAND_LOADCONTAINER_HELP,
  IDC_COMMAND_CONVERTCONTAINER_TITLE,
  IDC_COMMAND_CONVERTCONTAINER_HELP,
  IDC_PROTECTED_PREFIX,
  IDC_ENTER_PASSWORD,
  IDC_PASSWORD,
  IDC_PASSWORD_REPEAT,
  IDC_PASSWORD_EMPTY,
  IDC_PASSWORD_NOMATCH,
};

#endif // c4d_symbols_H

