
#ifndef c4d_symbols_H
#define c4d_symbols_H

enum
{
  IDC_OCONTAINER,
  IDC_TITLE_SELECTICON,
  IDC_INFO_OUTOFMEMORY,
  IDC_INFO_INVALIDIMAGE,
  IDC_TITLE_LOADSCENEFILE,
  IDC_INFO_INVALIDSCENEFILE,
  IDC_COMMAND_LOADCONTAINER_TITLE,
  IDC_COMMAND_LOADCONTAINER_HELP,
  IDC_COMMAND_CONVERTCONTAINER_TITLE,
  IDC_COMMAND_CONVERTCONTAINER_HELP,
  IDC_PASSWORD_ENTER,
  IDC_PASSWORD,
  IDC_PASSWORD_REPEAT,
  IDC_PASSWORD_EMPTY,
  IDC_PASSWORD_NOMATCH,
  IDC_PASSWORD_INVALID,
  IDS_CONTAINER_INFO,
};

#endif // c4d_symbols_H

