
#ifndef c4d_symbols_H
#define c4d_symbols_H

enum
{
  IDS_OCONTAINER,
  IDS_SELECTICON,
  IDS_INFO_OUTOFMEMORY,
  IDS_INFO_INVALIDIMAGE,
  IDS_TITLE_LOADSCENEFILE,
  IDS_INFO_INVALIDSCENEFILE,
  IDS_COMMAND_LOADCONTAINER_TITLE,
  IDS_COMMAND_LOADCONTAINER_HELP,
  IDS_COMMAND_CONVERTCONTAINER_TITLE,
  IDS_COMMAND_CONVERTCONTAINER_HELP,
  IDS_PASSWORD_ENTER,
  IDS_PASSWORD,
  IDS_PASSWORD_REPEAT,
  IDS_PASSWORD_EMPTY,
  IDS_PASSWORD_NOMATCH,
  IDS_PASSWORD_INVALID,
};

#endif // c4d_symbols_H

